#!/usr/bin/env bash
# Builds a single paste-able system prompt from the shared contract + orchestrator,
# so adoption is "paste ONE file" instead of loading three.
# Usage: bash scripts/build-bundle.sh   (run from repo root)
set -euo pipefail
cd "$(dirname "$0")/.."
OUT="dist/cx-agent-builder.system.md"
mkdir -p dist
{
  echo "<!-- AUTO-GENERATED by scripts/build-bundle.sh — do not edit by hand."
  echo "     Sources: shared/ground-truth.md + shared/output-contract.md + 00-orchestrator.prompt.md -->"
  echo
  echo "# ===== PLATFORM GROUND TRUTH ====="; echo
  cat shared/ground-truth.md; echo
  echo "# ===== GLOBAL OUTPUT CONTRACT ====="; echo
  cat shared/output-contract.md; echo
  echo "# ===== ORCHESTRATOR ====="; echo
  cat 00-orchestrator.prompt.md; echo
  echo "# ===== STAGE CONTRACTS (read the relevant one as you reach each stage) ====="; echo
  for f in 01-ingest 02-interview 03-design 04-build 05-evals 06-validate 07-debug-fix; do
    echo; echo "## ---- $f ----"; echo
    cat "$f.prompt.md"; echo
  done
} > "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
